services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: quicket
      POSTGRES_USER: quicket
      POSTGRES_PASSWORD: PASSword01!!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql # Changed for PostgreSQL 18+ compatibility
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quicket -d quicket"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: